import { useState } from "react";
import { Link } from "react-router-dom";
import Seo from "../../seo/Seo";
import routesName from "~routes/enum.routes";
import "./ZWCADMFGPage.css";

const CDN = "https://zwcdn.zwsoft.com/web/images/zwcad_mfg_ov";
const IMG = "/image-zwcad";
const STATICS = "https://statics.zwsoft.com/upload/admin/20240527";

const timingRows = [
  { task: "Part 1: Set up frame",           mfg: "00:34", zwcad: "01:44" },
  { task: "Part 2: Modify design",           mfg: "02:22", zwcad: "03:18" },
  { task: "Part 3: Create part drawing",     mfg: "03:25", zwcad: "05:44" },
  { task: "Part 4: Create assembly drawing", mfg: "01:50", zwcad: "05:58" },
];

const companyLogos = [
  { src: `${STATICS}/591b11b7338abb0f8646e67160e69182.png`, alt: "Gates" },
  { src: `${STATICS}/df6d98a7e0bb4eccc974d7b9faa5b5b7.png`, alt: "Zugspitze" },
  { src: `${STATICS}/d37371841ae91ff166b860bd1433291f.png`, alt: "CRRC" },
  { src: `${STATICS}/deb547381e01e3aefea7ca322ba38398.png`, alt: "LINGLONG TIRE" },
  { src: `${STATICS}/67d41fb1c3089cc935b271884176d61e.png`, alt: "DONGFENG" },
  { src: `${STATICS}/5fac18c9b592715b11e0c9c646254157.png`, alt: "WOLONG" },
  { src: `${STATICS}/fe26536c62fdc54c76f9f144626ee21d.png`, alt: "NWM" },
  { src: `${STATICS}/3508aac08fa2e194d366a0c7de4256c5.png`, alt: "ZHENDE MEDICAL" },
  { src: `${STATICS}/de9c97f21f3c2410e7990773b45f7124.png`, alt: "wencan" },
  { src: `${STATICS}/b6178192f5b1e00466997bb6ea2b17c6.png`, alt: "China Merchants" },
];

const testimonials = [
  {
    name: "Gates",
    post: "MFG-Automotive丨China",
    quote: "It is highly compatible with popular CAD software and runs smoothly even when you open multiple windows. Its part library is very huge and practical. You can directly use the parts in the library without having to draw them from scratch. This really lightens the load of our drawing work.",
    img: `${STATICS}/7b7058d4808066acbdfe8cf284571b1c.jpeg`,
    logo: `${STATICS}/591b11b7338abb0f8646e67160e69182.png`,
  },
  {
    name: "Linglong Tire",
    post: "MFG-Automative丨China",
    quote: "It boosts our design efficiency while cutting down on the expenses of software procurement and implementation.",
    img: `${STATICS}/2cb982c7ea2739c2c351b4c3a4f80db6.jpeg`,
    logo: `${STATICS}/deb547381e01e3aefea7ca322ba38398.png`,
  },
  {
    name: "Wolong",
    post: "MFG-Others丨China",
    quote: "It offers some unique functions that enhance our workflow, such as intelligent annotation, super card and detail view. The BOMs generated by it can seamlessly interact with PDM and ERP systems. This really boosts design efficiency.",
    img: `${STATICS}/50ee5334154e2d45c4b2392e678ac133.jpeg`,
    logo: `${STATICS}/5fac18c9b592715b11e0c9c646254157.png`,
  },
];

const relatedProducts = [
  { to: routesName.SAN_PHAM_ZWCAD, logo: `${IMG}/logo/zwcadmb`, name: "ZWCAD",  sub: "DWG-Compatible CAD for Better Productivity" },
  { to: routesName.SAN_PHAM_ZW3D,  logo: `${IMG}/logo/zwc3d`,   name: "ZW3D",   sub: "Affordable All-in-One 3D CAD/CAE/CAM" },
];

export default function ZWCADMFGPage() {
  const [videoOpen, setVideoOpen] = useState(false);

  return (
    <>
      <Seo
        title="ZWCAD MFG - Advanced 2D CAD for Manufacturing"
        description="ZWCAD MFG is an advanced CAD software for manufacturing to enhance overall efficiency with standard parts, intelligent tools, and PLM integration."
        keywords="zwcad mfg, manufacturing cad, mechanical drawing, bom, part library"
      />

      {/* ── Hero Banner ── */}
      <div className="da-main">
        <div
          className="da-bg pc"
          style={{ backgroundImage: `url('${CDN}/zwcad-mfg-2026.jpg')` }}
        />
        <div
          className="da-bg phone"
          style={{ backgroundImage: `url('${CDN}/zwcad-mfg-2026-b.jpg')` }}
        />
        <div className="da-text">
          <div className="da-box">
            <div className="da-namebox">
              <div className="da-logo">
                <img src="https://statics.zwsoft.com/upload/en/20250414/64beab377ae26f3ce4e89c31e84f8598.png" alt="ZWCAD MFG" />
              </div>
              <h1 className="da-name d-bold">ZWCAD MFG</h1>
            </div>
            <h2 className="da-titles d-bold">Advanced 2D CAD for Manufacturing</h2>
            <div className="da-textbox">
              <p><span className="da-nub d-bold">From $1,699,</span> You own it forever</p>
              <p>Perpetual and network licenses available.</p>
            </div>
            <div className="da-buttom">
              <Link className="da-trial d-bold" to={routesName.TAI_VE}>Start 30-day Free Trial</Link>
              <Link className="da-see d-bold white" to={routesName.LIEN_HE}>See Pricing</Link>
            </div>
          </div>
        </div>
      </div>

      {/* ── Video Modal ── */}
      {videoOpen && (
        <div className="mfg-modal" onClick={() => setVideoOpen(false)}>
          <div className="mfg-modal__inner" onClick={(e) => e.stopPropagation()}>
            <button className="mfg-modal__close" onClick={() => setVideoOpen(false)}>×</button>
            <iframe
              src="https://fast.wistia.net/embed/iframe/pmom8zvt2r?autoPlay=1"
              allowFullScreen
              className="mfg-modal__iframe"
              title="ZWCAD MFG Overview"
            />
          </div>
        </div>
      )}

      {/* ── What's ZWCAD MFG ── */}
      <div className="db-main">
        <div className="db-inner">
          <div className="db-cont">
            <div className="db-left">
              <div className="db-imgbox" onClick={() => setVideoOpen(true)}>
                <div className="db-img">
                  <img src={`${CDN}/da24.png`} alt="ZWCAD MFG Overview" />
                </div>
                <div className="db-play" />
              </div>
            </div>
            <div className="db-right">
              <div className="db-titles d-bold">What's ZWCAD MFG</div>
              <h2 className="db-subtitle d-bold">
                Advanced CAD Solution to <span className="db-span d-bold">Enhance Overall Manufacturing Efficiency</span>
              </h2>
              <p className="db-intro">
                Built on the powerful ZWCAD platform, it enables users to create standardized, high-quality designs easier and faster by offering an extensive library of standard parts, intelligent drawing tools, and other productivity-enhancing features.
              </p>
              <p className="db-intro" style={{ marginTop: 16 }}>
                Moreover, it can be seamlessly integrated into PLM systems to achieve efficient management throughout the product lifecycle.
              </p>
              <div className="db-btns">
                <Link className="db-btn-fill d-bold" to={routesName.TAI_VE}>Start Free Trial</Link>
                <Link className="db-btn-ghost" to={routesName.LIEN_HE}>See Pricing →</Link>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ── Feature 1: Standard parts library (card bg) ── */}
      <div className="dc-main">
        <div className="dc-inner">
          <div className="dc-cont">
            <div className="dc-left">
              <div className="dc-titles d-bold">Why ZWCAD MFG</div>
              <h2 className="dc-subtitle d-bold">
                Create standard drawings with <span className="dc-span d-bold">an extensive library of standard parts</span>
              </h2>
              <p className="dc-intro">
                Quickly create drawings compliant with national and international standards, including ISO, EN, DIN, ANSI, ASME, PN, IS, JIS and more. From bolts to screws, and rivets to studs, you'll find the right parts for every project.
              </p>
            </div>
            <div className="dc-right">
              <div className="dc-img">
                <img src={`${CDN}/extensive-library-of-standard-parts.png`} alt="compliant with ISO, EN, DIN, ANSI and more" />
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ── Feature 2: Intelligent tools (no bg, reversed) ── */}
      <div className="de-main">
        <div className="de-inner">
          <div className="de-cont">
            <div className="de-left">
              <h2 className="de-subtitle d-bold">
                <span className="de-span d-bold">Speed up your design process</span> with intelligent tools
              </h2>
              <p className="de-intro">
                Automate and accelerate your design workflow with a rich set of drawing tools, intelligent annotation tools, an extensive symbol library and automatic BOMs associated with balloons and part properties.
              </p>
            </div>
            <div className="de-right">
              <div className="de-img">
                <img src={`${CDN}/rich-set-of-drawing-tools.png`} alt="rich set of drawing tools" />
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ── Feature 3: Unify design standards (card bg) ── */}
      <div className="dc-main">
        <div className="dc-inner">
          <div className="dc-cont">
            <div className="dc-left">
              <h2 className="dc-subtitle d-bold">
                <span className="dc-span d-bold">Unify design standards</span> across your team with customizations
              </h2>
              <p className="dc-intro">
                Build your own templates with customizable border frames, part library, dimension styles, fonts, technical requirements, and more. Consistent standards across your team ensure accuracy and alignment from start to finish.
              </p>
            </div>
            <div className="dc-right">
              <div className="dc-img">
                <img src={`${CDN}/unify-design-standards-with-customizations.png`} alt="build own templates across teams" />
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ── Feature 4: PLM integration (no bg, reversed) ── */}
      <div className="de-main">
        <div className="de-inner">
          <div className="de-cont">
            <div className="de-left">
              <h2 className="de-subtitle d-bold">
                Manage data and enhance collaboration through <span className="de-span d-bold">PLM integration</span>
              </h2>
              <p className="de-intro">
                Seamlessly integrate with popular PLM systems, such as Teamcenter<sup>®</sup> and Windchill<sup>®</sup> to manage design data more efficiently and strengthen team collaboration.
              </p>
            </div>
            <div className="de-right">
              <div className="de-img">
                <img src={`${CDN}/plm-integration.png`} alt="integrate with popular PLM systems" />
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ── Benefits: Comparison table ── */}
      <div className="df-main">
        <div className="df-inner">
          <div className="df-cont">
            <div className="df-left">
              <h2 className="df-titles d-bold">Benefits of Using ZWCAD MFG</h2>
              <p className="df-intro">
                We conducted a comprehensive comparison between ZWCAD and ZWCAD MFG, using a hand pump as an example to perform common design tasks from drafting to detailing. The results revealed that ZWCAD MFG significantly boosted productivity by 51% compared to ZWCAD.
              </p>
              <div className="df-buttom">
                <button type="button" className="df-video-btn d-bold" onClick={() => setVideoOpen(true)}>
                  Watch the video
                </button>
                <a
                  className="df-more d-bold"
                  href="https://dl.zwsoft.com/market/website_file/Benefits_of_Using_ZWCAD_MFG.pdf"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Learn More
                </a>
              </div>
            </div>
            <div className="df-right">
              <div className="df-table">
                <div className="df-box">
                  <div className="df-tr">
                    <span className="df-th d-bold">Project tasks</span>
                    <span className="df-th d-bold">ZWCAD MFG</span>
                    <span className="df-th d-bold">ZWCAD</span>
                  </div>
                  <div className="df-list">
                    {timingRows.map((r) => (
                      <div key={r.task} className="df-item">
                        <div className="df-td">
                          <div className="df-lt">
                            <span className="df-name">{r.task}</span>
                          </div>
                        </div>
                        <div className="df-td">
                          <div className="df-time">{r.mfg}</div>
                        </div>
                        <div className="df-td">
                          <div className="df-time">{r.zwcad}</div>
                        </div>
                      </div>
                    ))}
                  </div>
                  <div className="df-tr" style={{ borderTop: "1px solid rgba(228,230,240,.5)", marginTop: 0 }}>
                    <span className="df-th d-bold">Total Time</span>
                    <span className="df-th d-bold">08:11</span>
                    <span className="df-th d-bold" style={{ color: "#000" }}>16:44</span>
                  </div>
                  <div className="df-score d-bold">51% productivity boost 🚀</div>
                  <div className="df-hint">* Based on internal testing with hand pump design tasks</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ── Testimonials ── */}
      <div className="di-main">
        <div className="di-inner">
          <div className="di-top">
            <h2 className="di-titles d-bold">They <span className="di-span d-bold">Choose</span> Us</h2>
            <p className="di-synopsis">Trusted by leading companies worldwide</p>
          </div>
          <div className="di-center">
            {companyLogos.map((l) => (
              <div key={l.alt} className="di-logo">
                <img src={l.src} alt={l.alt} />
              </div>
            ))}
          </div>
        </div>
        <div className="di-marquee">
          <div className="di-track">
            {[...testimonials, ...testimonials].map((s, i) => (
              <div key={i} className="dib-item">
                <div className="dib-link">
                  <div className="dib-right">
                    <div className="dib-top">
                      <div className="dib-quot">
                        <img src="https://zwcdn.zwsoft.com/web/images/zwcad_ov/da13.png" alt="" />
                      </div>
                      <div className="dib-intro">{s.quote}</div>
                    </div>
                    <div className="dib-bottom">
                      <div className="dib-lt">
                        <div className="dib-name d-bold">{s.name}</div>
                        <div className="dib-post">{s.post}</div>
                      </div>
                      <div className="dib-rt">
                        <div className="dib-logo">
                          <img src={s.logo} alt={s.name} />
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="dib-left">
                    <div className="dib-img">
                      <img src={s.img} alt={s.name} />
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* ── Related products ── */}
      <div className="dl-main">
        <div className="dl-inner">
          <h2 className="dl-titles d-bold">Explore More Products</h2>
          <div className="dl-cont">
            {relatedProducts.map((p) => (
              <Link key={p.name} to={p.to} className="dl-item">
                <div className="dl-img">
                  <img src={p.logo} alt={p.name} />
                </div>
                <div className="dl-name d-bold">{p.name}</div>
                <div className="dl-intro">{p.sub}</div>
                <span className="dl-link">Learn more →</span>
              </Link>
            ))}
          </div>
        </div>
      </div>

      {/* ── CTA ── */}
      <div className="gu-main">
        <div className="gu-inner">
          <h2 className="gu-title g-size36 d-bold">Get started with ZWCAD MFG today</h2>
          <p className="gu-des g-size20">Revolutionize the way you create — enjoy a 30-day free trial.</p>
          <div className="gu-btns">
            <Link className="d-bold white" to={routesName.TAI_VE}>Start Free Trial</Link>
            <Link className="d-bold" to={routesName.LIEN_HE}>Contact Sales</Link>
          </div>
        </div>
      </div>
    </>
  );
}
