import { useState } from "react";
import { Link } from "react-router-dom";
import Seo from "../../seo/Seo";
import AwardSection from "../ProductPage/AwardSection/AwardSection";
import ReviewSection from "../ProductPage/ReviewSection/ReviewSection";
import routesName from "~routes/enum.routes";
import "./ZWCADMFGPage.css";

const CDN = "https://zwcdn.zwsoft.com/web/images/zwcad_mfg_ov";
const IMG = "/image-zwcad";

const whyFeatures = [
  {
    title: "Create standard drawings with an extensive library of standard parts",
    desc: "Quickly create drawings compliant with national and international standards, including ISO, EN, DIN, ANSI, ASME, PN, IS, JIS and more. From bolts to screws, and rivets to studs, you'll find the right parts for every project.",
    img: `${IMG}/zwcad/da40.png`,
  },
  {
    title: "Speed up your design process with intelligent tools",
    desc: "Automate and accelerate your design workflow with a rich set of drawing tools, intelligent annotation tools, an extensive symbol library and automatic BOMs associated with balloons and part properties.",
    img: `${IMG}/zwcad/da37.png`,
  },
  {
    title: "Unify design standards across your team with customizations",
    desc: "Build your own templates with customizable border frames, part library, dimension styles, fonts, technical requirements, and more. Consistent standards across your team ensure accuracy and alignment from start to finish.",
    img: `${IMG}/zwcad/da38.png`,
  },
  {
    title: "Manage data and enhance collaboration through PLM integration",
    desc: "Seamlessly integrate with popular PLM systems, such as Teamcenter® and Windchill® to manage design data more efficiently and strengthen team collaboration.",
    img: `${IMG}/zwcad/da41.png`,
  },
];

const timingRows = [
  { task: "Part 1: Set up frame",           mfg: "00:34", zwcad: "01:44" },
  { task: "Part 2: Modify design",           mfg: "02:22", zwcad: "03:18" },
  { task: "Part 3: Create part drawing",     mfg: "03:25", zwcad: "05:44" },
  { task: "Part 4: Create assembly drawing", mfg: "01:50", zwcad: "05:58" },
];

const testimonials = [
  {
    name: "Gates",
    post: "MFG-Automotive | China",
    quote: "It is highly compatible with popular CAD software and runs smoothly even when you open multiple windows. Its part library is very huge and practical. You can directly use the parts in the library without having to draw them from scratch.",
    img: `${IMG}/lpyeah2025/re3.png`,
    logo: `${IMG}/lpyeah2025/re_logo3.svg`,
  },
  {
    name: "Linglong Tire",
    post: "MFG-Automotive | China",
    quote: "It boosts our design efficiency while cutting down on the expenses of software procurement and implementation.",
    img: `${IMG}/lpyeah2025/re5.png`,
    logo: `${IMG}/lpyeah2025/re_logo5.svg`,
  },
  {
    name: "Wolong",
    post: "MFG-Others | China",
    quote: "It offers some unique functions that enhance our workflow, such as intelligent annotation, super card and detail view. The BOMs generated by it can seamlessly interact with PDM and ERP systems.",
    img: `${IMG}/lpyeah2025/re1.png`,
    logo: `${IMG}/lpyeah2025/re_logo1.svg`,
  },
];

const relatedProducts = [
  { to: routesName.SAN_PHAM_ZWCAD, logo: `${IMG}/logo/zwcadmb`, name: "ZWCAD",     sub: "DWG-Compatible CAD for Better Productivity" },
  { to: routesName.SAN_PHAM_ZW3D,  logo: `${IMG}/logo/zwc3d`,   name: "ZW3D",      sub: "Affordable All-in-One 3D CAD/CAE/CAM" },
];

export default function ZWCADMFGPage() {
  const [videoOpen, setVideoOpen] = useState(false);

  return (
    <>
      <Seo
        title="ZWCAD MFG - Advanced 2D CAD for Manufacturing"
        description="ZWCAD MFG is an advanced CAD software for manufacturing to enhance overall efficiency with standard parts, intelligent tools, and PLM integration."
        keywords="zwcad mfg, manufacturing cad, mechanical drawing, bom, part library"
      />

      <div className="mfg-page">

        {/* ── Banner / Hero ── */}
        <div className="mfg-banner">
          <div className="mfg-banner__overlay" />
          <div className="container mfg-banner__inner">
            <div className="mfg-banner__left">
              <div className="mfg-banner__tag">ZWCAD MFG</div>
              <h1 className="mfg-banner__title">
                Advanced 2D CAD<br />for Manufacturing
              </h1>
              <p className="mfg-banner__sub">
                From $1,699 — you own it forever. Perpetual and network licenses available.
              </p>
              <div className="mfg-banner__btns">
                <Link className="mfg-btn-fill" to={routesName.TAI_VE}>Start 30-day Free Trial</Link>
                <Link className="mfg-btn-line" to={routesName.LIEN_HE}>Buy Now</Link>
              </div>
            </div>
            <div className="mfg-banner__right">
              <div className="mfg-banner__video-wrap" onClick={() => setVideoOpen(true)}>
                <img
                  src={`${CDN}/da29.png`}
                  alt="Watch ZWCAD MFG Overview"
                  className="mfg-banner__video-thumb"
                  onError={(e) => { (e.currentTarget as HTMLImageElement).src = `${IMG}/zwcad/comparison.gif`; }}
                />
                <button className="mfg-play-btn" aria-label="Play video">
                  <svg viewBox="0 0 24 24" fill="white"><path d="M8 5v14l11-7z"/></svg>
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* ── Wistia video modal ── */}
        {videoOpen && (
          <div className="mfg-modal" onClick={() => setVideoOpen(false)}>
            <div className="mfg-modal__inner" onClick={(e) => e.stopPropagation()}>
              <button className="mfg-modal__close" onClick={() => setVideoOpen(false)}>×</button>
              <iframe
                src="https://fast.wistia.net/embed/iframe/pmom8zvt2r?autoPlay=1"
                allowFullScreen
                className="mfg-modal__iframe"
                title="ZWCAD MFG Overview"
              />
            </div>
          </div>
        )}

        {/* ── What's ZWCAD MFG ── */}
        <div className="mfg-ctn1">
          <div className="container mfg-ctn1__inner">
            <div className="mfg-ctn1__img">
              <img src={`${IMG}/zwcad/da45.png`} alt="ZWCAD MFG overview" />
            </div>
            <div className="mfg-ctn1__text">
              <div className="mfg-s-tag">What's ZWCAD MFG</div>
              <h2 className="mfg-s-title">
                Advanced CAD Solution to Enhance Overall<br /><span className="mfg-accent">Manufacturing Efficiency</span>
              </h2>
              <p className="mfg-s-desc">
                Built on the powerful ZWCAD platform, it enables users to create standardized, high-quality designs easier and faster by offering an extensive library of standard parts, intelligent drawing tools, and other productivity-enhancing features.
              </p>
              <p className="mfg-s-desc">
                Moreover, it can be seamlessly integrated into PLM systems to achieve efficient management throughout the product lifecycle.
              </p>
              <div className="mfg-ctn1__btns">
                <Link className="mfg-btn-fill" to={routesName.TAI_VE}>Start Free Trial</Link>
                <Link className="mfg-btn-ghost" to={routesName.LIEN_HE}>See Pricing →</Link>
              </div>
            </div>
          </div>
        </div>

        {/* ── Why ZWCAD MFG (4 feature blocks) ── */}
        <div className="mfg-ctn4">
          <div className="container">
            <h2 className="mfg-s-title mfg-center">Why ZWCAD MFG</h2>
            <div className="mfg-altfeats">
              {whyFeatures.map((f, i) => (
                <div key={f.title} className={`mfg-altfeat${i % 2 !== 0 ? " mfg-altfeat--rev" : ""}`}>
                  <div className="mfg-altfeat__img">
                    <img src={f.img} alt={f.title} />
                  </div>
                  <div className="mfg-altfeat__body">
                    <h3 className="mfg-altfeat__title">{f.title}</h3>
                    <p className="mfg-altfeat__desc">{f.desc}</p>
                    <Link className="mfg-altfeat__link" to={routesName.TAI_VE}>Learn more →</Link>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* ── Benefits / Comparison (bg2) ── */}
        <div className="mfg-ctn5">
          <div className="container mfg-ctn5__inner">
            <div className="mfg-ctn5__left">
              <div className="mfg-s-tag" style={{ background: "rgba(255,255,255,.15)", border: "1px solid rgba(255,255,255,.4)" }}>Benefits of Using ZWCAD MFG</div>
              <h2 className="mfg-s-title mfg-white">
                Boost Productivity by <span style={{ color: "#7dd87d" }}>51%</span>
              </h2>
              <p className="mfg-s-desc mfg-white-sub">
                We compared ZWCAD and ZWCAD MFG using a hand pump as an example — performing common design tasks from drafting to detailing. ZWCAD MFG significantly boosted productivity by 51% compared to ZWCAD.
              </p>
              <div className="mfg-compare-table">
                <div className="mfg-compare-head">
                  <span>Project Task</span>
                  <span className="mfg-col-mfg">ZWCAD MFG</span>
                  <span>ZWCAD</span>
                </div>
                {timingRows.map((r) => (
                  <div key={r.task} className="mfg-compare-row">
                    <span>{r.task}</span>
                    <span className="mfg-col-mfg">{r.mfg}</span>
                    <span>{r.zwcad}</span>
                  </div>
                ))}
                <div className="mfg-compare-row mfg-compare-row--total">
                  <span><strong>Total Time</strong></span>
                  <span className="mfg-col-mfg"><strong>08:11</strong></span>
                  <span><strong>16:44</strong></span>
                </div>
              </div>
              <Link className="mfg-btn-fill mfg-ctn5__cta" to={routesName.LIEN_HE}>Get a Quote</Link>
            </div>
            <div className="mfg-ctn5__right">
              <div className="mfg-ctn5__imggrid">
                {[da46, da47, da48, da52].map((src, i) => (
                  <div key={i} className="mfg-ctn5__imgitem">
                    <img src={src} alt="ZWCAD MFG feature" />
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* ── Testimonials ── */}
        <div className="mfg-cases">
          <div className="container">
            <h2 className="mfg-s-title mfg-center">They Choose Us</h2>
            <p className="mfg-s-desc mfg-center" style={{ maxWidth: 560, margin: "0 auto 40px" }}>
              Trusted by leading manufacturing companies worldwide
            </p>
          </div>
          <div className="di-marquee">
            <div className="di-marquee-track">
              {[...testimonials, ...testimonials].map((s, i) => (
                <div key={i} className="dib-item">
                  <div className="dib-img"><img src={s.img} alt={s.name} /></div>
                  <div className="dib-body">
                    <div className="dib-quot">"</div>
                    <div className="dib-intro">{s.quote}</div>
                    <div className="dib-footer">
                      <div>
                        <div className="dib-name">{s.name}</div>
                        <div className="dib-post">{s.post}</div>
                      </div>
                      <img className="dib-logo-img" src={s.logo} alt={s.name} />
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* ── Awards & Reviews ── */}
        <AwardSection />
        <ReviewSection />

        {/* ── CTA (bg3) ── */}
        <div className="mfg-ctn7">
          <div className="mfg-ctn7__overlay" />
          <div className="container mfg-ctn7__inner">
            <div className="mfg-ctn7__left">
              <h3 className="mfg-ctn7__title">Get started with ZWCAD MFG today</h3>
              <p className="mfg-ctn7__sub">Revolutionize the way you create — enjoy a 30-day free trial.</p>
            </div>
            <div className="mfg-ctn7__right">
              <Link className="mfg-btn-fill" to={routesName.TAI_VE}>Start 30-day Free Trial</Link>
              <Link className="mfg-btn-line" to={routesName.LIEN_HE}>Buy Now</Link>
              <Link className="mfg-btn-line" to={routesName.LIEN_HE}>Contact Sales</Link>
            </div>
          </div>
        </div>

        {/* ── Related products ── */}
        <div className="mfg-ctn8">
          <div className="container">
            <h2 className="mfg-s-title mfg-center">Explore More Products</h2>
            <div className="mfg-related">
              {relatedProducts.map((p) => (
                <Link key={p.name} to={p.to} className="mfg-related__card">
                  <div className="mfg-related__logo">
                    <img src={p.logo} alt={p.name} />
                  </div>
                  <h3 className="mfg-related__name">{p.name}</h3>
                  <p className="mfg-related__sub">{p.sub}</p>
                  <span className="mfg-related__link">Learn more →</span>
                </Link>
              ))}
            </div>
          </div>
        </div>

      </div>
    </>
  );
}

const da46 = "/image-zwcad/zwcad/da46.png";
const da47 = "/image-zwcad/zwcad/da47.png";
const da48 = "/image-zwcad/zwcad/da48.png";
const da52 = "/image-zwcad/zwcad/da52.png";
