const routesName = {
  ROOT: "/",
  TRANG_CHU: "/trang-chu",
  SAN_PHAM: "/san-pham/:productSlug",
  SAN_PHAM_ZWCAD: "/san-pham/zwcad",
  SAN_PHAM_ZW3D: "/san-pham/zw3d",
  SAN_PHAM_ZWCAD_MFG: "/san-pham/zwcad-mfg",
  SAN_PHAM_ZWCAD_LEGACY: "/san-pham-zwcad",
  TIN_TUC: "/tin-tuc",
  TIN_TUC_DETAIL: "/tin-tuc/:slug",
  TAI_VE: "/tai-ve",
  TAI_VE_DETAIL: "/tai-ve/:slug",
  FAQ: "/cau-hoi-thuong-gap",
  FAQ_DETAIL: "/cau-hoi-thuong-gap/:slug",
  LIEN_HE: "/lien-he",
  ADMIN_LOGIN: "/admin/login",
  ADMIN_DASHBOARD: "/admin",
  ADMIN_BANNERS: "/admin/banners",
  ADMIN_NEWS: "/admin/news",
  ADMIN_FAQ: "/admin/faq",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_DOWNLOADS: "/admin/downloads",
  ADMIN_CONTACTS: "/admin/contacts",
} as const;

export default routesName;
